"""Генератор прикладных проектов для курса DataMath.

Создаёт ноутбуки в стиле 15_Supermarket_Analysis.ipynb:
- русский язык, синтетические данные, EDA, применение теории курса, упражнения.
"""
import nbformat as nbf


def md(text):
    return nbf.v4.new_markdown_cell(text)


def code(text):
    return nbf.v4.new_code_cell(text)


def build_notebook(cells):
    nb = nbf.v4.new_notebook()
    nb.cells = cells
    nb.metadata = {"language_info": {"name": "python"}}
    return nb


# =====================================================================
# ПРОЕКТ 16: A/B-тестирование
# =====================================================================
def project_ab_testing():
    cells = []

    cells.append(md(
        "# A/B-тестирование новой версии сайта\n"
        "\n"
        "## Прикладной проект: Оценка эффективности изменения интерфейса\n"
        "\n"
        "В этом ноутбуке мы применим знания из **Модуля 3 (Выводная статистика)** для "
        "анализа результатов A/B-теста интернет-магазина.\n"
        "\n"
        "Компания изменила кнопку оформления заказа и хочет понять, действительно ли новая "
        "версия (**B**) увеличивает конверсию по сравнению со старой (**A**), или разница "
        "случайна.\n"
        "\n"
        "### Содержание:\n"
        "1. Загрузка и предобработка данных\n"
        "2. Exploratory Data Analysis (EDA)\n"
        "3. Доверительные интервалы для конверсий\n"
        "4. Проверка гипотез: z-тест для двух пропорций\n"
        "5. Размер эффекта и мощность теста\n"
        "6. Байесовский взгляд на A/B-тест (Beta-Binomial)\n"
        "7. Выводы и рекомендации"
    ))

    cells.append(code(
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n"
        "from scipy import stats\n"
        "import warnings\n"
        "warnings.filterwarnings('ignore')\n"
        "\n"
        "plt.style.use('seaborn-v0_8-whitegrid')\n"
        "sns.set_palette('husl')\n"
        "\n"
        "print('Библиотеки успешно загружены!')"
    ))

    cells.append(md(
        "## 1. Загрузка и предобработка данных\n"
        "\n"
        "Сгенерируем синтетические данные A/B-теста, имитирующие реальный трафик сайта.\n"
        "\n"
        "### Структура данных:\n"
        "- **user_id**: Уникальный идентификатор пользователя\n"
        "- **group**: Группа теста (`A` — контроль, `B` — новая версия)\n"
        "- **converted**: Совершил ли пользователь покупку (1) или нет (0)\n"
        "- **time_on_site**: Время на сайте в секундах"
    ))

    cells.append(code(
        "# Генерация синтетических данных A/B-теста\n"
        "np.random.seed(42)\n"
        "\n"
        "# Истинные (неизвестные аналитику) конверсии групп\n"
        "true_conv_A = 0.120   # контроль\n"
        "true_conv_B = 0.138   # новая версия (эффект +1.8 п.п.)\n"
        "\n"
        "n_A = 5000  # пользователей в группе A\n"
        "n_B = 5000  # пользователей в группе B\n"
        "\n"
        "# Генерация конверсий (распределение Бернулли)\n"
        "conv_A = np.random.binomial(1, true_conv_A, n_A)\n"
        "conv_B = np.random.binomial(1, true_conv_B, n_B)\n"
        "\n"
        "# Время на сайте (лог-нормальное распределение)\n"
        "time_A = np.random.lognormal(mean=4.8, sigma=0.5, size=n_A)\n"
        "time_B = np.random.lognormal(mean=4.9, sigma=0.5, size=n_B)\n"
        "\n"
        "df = pd.DataFrame({\n"
        "    'user_id': np.arange(1, n_A + n_B + 1),\n"
        "    'group': ['A'] * n_A + ['B'] * n_B,\n"
        "    'converted': np.concatenate([conv_A, conv_B]),\n"
        "    'time_on_site': np.round(np.concatenate([time_A, time_B]), 1)\n"
        "})\n"
        "\n"
        "# Перемешаем строки\n"
        "df = df.sample(frac=1, random_state=42).reset_index(drop=True)\n"
        "\n"
        "print('Данные A/B-теста')\n"
        "print('=' * 60)\n"
        "print(f'Всего пользователей: {len(df)}')\n"
        "print(f'Группа A: {(df[\"group\"] == \"A\").sum()}')\n"
        "print(f'Группа B: {(df[\"group\"] == \"B\").sum()}')\n"
        "print(f'\\nПервые 10 строк:')\n"
        "print(df.head(10))"
    ))

    cells.append(md(
        "## 2. Exploratory Data Analysis (EDA)\n"
        "\n"
        "Оценим наблюдаемые конверсии и распределение времени на сайте."
    ))

    cells.append(code(
        "# Сводка по группам\n"
        "summary = df.groupby('group').agg(\n"
        "    users=('user_id', 'count'),\n"
        "    conversions=('converted', 'sum'),\n"
        "    conv_rate=('converted', 'mean'),\n"
        "    avg_time=('time_on_site', 'mean')\n"
        ")\n"
        "summary['conv_rate_%'] = (summary['conv_rate'] * 100).round(2)\n"
        "\n"
        "print('Сводная статистика по группам')\n"
        "print('=' * 60)\n"
        "print(summary)\n"
        "\n"
        "p_A = summary.loc['A', 'conv_rate']\n"
        "p_B = summary.loc['B', 'conv_rate']\n"
        "print(f'\\nНаблюдаемая конверсия A: {p_A*100:.2f}%')\n"
        "print(f'Наблюдаемая конверсия B: {p_B*100:.2f}%')\n"
        "print(f'Абсолютная разница: {(p_B - p_A)*100:.2f} п.п.')\n"
        "print(f'Относительный прирост: {(p_B/p_A - 1)*100:.2f}%')"
    ))

    cells.append(code(
        "# Визуализация EDA\n"
        "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n"
        "\n"
        "# 1. Конверсия по группам\n"
        "conv_rates = [p_A * 100, p_B * 100]\n"
        "axes[0, 0].bar(['A (контроль)', 'B (новая)'], conv_rates,\n"
        "               color=['steelblue', 'coral'], alpha=0.7)\n"
        "for i, v in enumerate(conv_rates):\n"
        "    axes[0, 0].text(i, v + 0.1, f'{v:.2f}%', ha='center', fontweight='bold')\n"
        "axes[0, 0].set_ylabel('Конверсия (%)')\n"
        "axes[0, 0].set_title('Конверсия по группам')\n"
        "\n"
        "# 2. Количество конверсий\n"
        "convs = [summary.loc['A', 'conversions'], summary.loc['B', 'conversions']]\n"
        "axes[0, 1].bar(['A', 'B'], convs, color=['steelblue', 'coral'], alpha=0.7)\n"
        "axes[0, 1].set_ylabel('Количество покупок')\n"
        "axes[0, 1].set_title('Абсолютное число конверсий')\n"
        "\n"
        "# 3. Распределение времени на сайте\n"
        "axes[1, 0].hist(df[df['group'] == 'A']['time_on_site'], bins=40, alpha=0.6,\n"
        "                label='A', color='steelblue')\n"
        "axes[1, 0].hist(df[df['group'] == 'B']['time_on_site'], bins=40, alpha=0.6,\n"
        "                label='B', color='coral')\n"
        "axes[1, 0].set_xlabel('Время на сайте (сек)')\n"
        "axes[1, 0].set_ylabel('Количество')\n"
        "axes[1, 0].set_title('Распределение времени на сайте')\n"
        "axes[1, 0].legend()\n"
        "\n"
        "# 4. Boxplot времени по группам\n"
        "df.boxplot(column='time_on_site', by='group', ax=axes[1, 1])\n"
        "axes[1, 1].set_xlabel('Группа')\n"
        "axes[1, 1].set_ylabel('Время на сайте (сек)')\n"
        "axes[1, 1].set_title('Время на сайте по группам')\n"
        "plt.suptitle('')\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ))

    cells.append(md(
        "## 3. Доверительные интервалы для конверсий\n"
        "\n"
        "Конверсия — это доля (пропорция). Доверительный интервал для пропорции "
        "(нормальное приближение Вальда):\n"
        "\n"
        "$$\\hat{p} \\pm z_{\\alpha/2} \\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}}$$\n"
        "\n"
        "где $z_{\\alpha/2}$ — квантиль стандартного нормального распределения "
        "(для 95% доверия $z \\approx 1.96$)."
    ))

    cells.append(code(
        "# Доверительные интервалы для пропорций (95%)\n"
        "def proportion_ci(successes, n, confidence=0.95):\n"
        "    p = successes / n\n"
        "    z = stats.norm.ppf(1 - (1 - confidence) / 2)\n"
        "    se = np.sqrt(p * (1 - p) / n)\n"
        "    return p, p - z * se, p + z * se\n"
        "\n"
        "s_A = int(summary.loc['A', 'conversions'])\n"
        "s_B = int(summary.loc['B', 'conversions'])\n"
        "\n"
        "p_A, lo_A, hi_A = proportion_ci(s_A, n_A)\n"
        "p_B, lo_B, hi_B = proportion_ci(s_B, n_B)\n"
        "\n"
        "print('95% доверительные интервалы для конверсии')\n"
        "print('=' * 60)\n"
        "print(f'Группа A: {p_A*100:.2f}%  ДИ = [{lo_A*100:.2f}%, {hi_A*100:.2f}%]')\n"
        "print(f'Группа B: {p_B*100:.2f}%  ДИ = [{lo_B*100:.2f}%, {hi_B*100:.2f}%]')\n"
        "\n"
        "# Визуализация ДИ\n"
        "fig, ax = plt.subplots(figsize=(9, 5))\n"
        "groups = ['A (контроль)', 'B (новая)']\n"
        "means = [p_A * 100, p_B * 100]\n"
        "errors = [[(p_A - lo_A) * 100, (p_B - lo_B) * 100],\n"
        "          [(hi_A - p_A) * 100, (hi_B - p_B) * 100]]\n"
        "\n"
        "ax.errorbar(groups, means, yerr=errors, fmt='o', capsize=10,\n"
        "            markersize=10, color='darkblue', ecolor='gray', elinewidth=2)\n"
        "ax.set_ylabel('Конверсия (%)')\n"
        "ax.set_title('Конверсии с 95% доверительными интервалами')\n"
        "for i, v in enumerate(means):\n"
        "    ax.text(i + 0.05, v, f'{v:.2f}%', va='center', fontweight='bold')\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "if lo_B > hi_A:\n"
        "    print('\\nДоверительные интервалы НЕ пересекаются — есть основания считать B лучше.')\n"
        "else:\n"
        "    print('\\nДоверительные интервалы пересекаются — нужна формальная проверка гипотез.')"
    ))

    cells.append(md(
        "## 4. Проверка гипотез: z-тест для двух пропорций\n"
        "\n"
        "Формулируем гипотезы:\n"
        "- $H_0$: $p_A = p_B$ (новая версия не влияет на конверсию)\n"
        "- $H_1$: $p_A \\ne p_B$ (конверсии различаются)\n"
        "\n"
        "Статистика z-теста для двух пропорций:\n"
        "\n"
        "$$z = \\frac{\\hat{p}_B - \\hat{p}_A}{\\sqrt{\\hat{p}(1-\\hat{p})\\left(\\frac{1}{n_A}+\\frac{1}{n_B}\\right)}}, "
        "\\quad \\hat{p} = \\frac{x_A + x_B}{n_A + n_B}$$"
    ))

    cells.append(code(
        "# z-тест для двух пропорций\n"
        "p_pool = (s_A + s_B) / (n_A + n_B)\n"
        "se_pool = np.sqrt(p_pool * (1 - p_pool) * (1/n_A + 1/n_B))\n"
        "z_stat = (p_B - p_A) / se_pool\n"
        "p_value = 2 * (1 - stats.norm.cdf(abs(z_stat)))\n"
        "\n"
        "alpha = 0.05\n"
        "print('z-тест для двух пропорций')\n"
        "print('=' * 60)\n"
        "print(f'Объединённая пропорция p_pool: {p_pool:.4f}')\n"
        "print(f'z-статистика: {z_stat:.4f}')\n"
        "print(f'p-значение: {p_value:.4f}')\n"
        "print(f'Уровень значимости alpha: {alpha}')\n"
        "print('-' * 60)\n"
        "if p_value < alpha:\n"
        "    print('Отвергаем H0: различие статистически значимо.')\n"
        "else:\n"
        "    print('Не отвергаем H0: различие не значимо.')\n"
        "\n"
        "# Проверим с помощью хи-квадрат теста (эквивалентно для 2x2)\n"
        "contingency = np.array([[s_A, n_A - s_A], [s_B, n_B - s_B]])\n"
        "chi2, p_chi2, dof, expected = stats.chi2_contingency(contingency, correction=False)\n"
        "print(f'\\nПроверка хи-квадрат тестом: chi2 = {chi2:.4f}, p = {p_chi2:.4f}')\n"
        "print(f'(z^2 = {z_stat**2:.4f} должно совпадать с chi2)')"
    ))

    cells.append(code(
        "# Визуализация распределения z-статистики\n"
        "fig, ax = plt.subplots(figsize=(10, 6))\n"
        "x = np.linspace(-4, 4, 1000)\n"
        "ax.plot(x, stats.norm.pdf(x), 'b-', label='N(0,1) при H0')\n"
        "\n"
        "z_crit = stats.norm.ppf(1 - alpha / 2)\n"
        "ax.fill_between(x, 0, stats.norm.pdf(x), where=(np.abs(x) >= z_crit),\n"
        "                color='red', alpha=0.3, label='Область отклонения H0')\n"
        "ax.axvline(z_stat, color='green', linestyle='--', linewidth=2,\n"
        "           label=f'z = {z_stat:.2f}')\n"
        "ax.axvline(-z_crit, color='red', linestyle=':', alpha=0.7)\n"
        "ax.axvline(z_crit, color='red', linestyle=':', alpha=0.7)\n"
        "ax.set_xlabel('z')\n"
        "ax.set_ylabel('Плотность')\n"
        "ax.set_title('z-тест: наблюдаемая статистика и критическая область')\n"
        "ax.legend()\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ))

    cells.append(md(
        "## 5. Размер эффекта и мощность теста\n"
        "\n"
        "p-значение говорит о статистической значимости, но не о **величине** эффекта. "
        "Оценим размер эффекта (Cohen's h) и мощность теста."
    ))

    cells.append(code(
        "# Размер эффекта Cohen's h для пропорций\n"
        "def cohens_h(p1, p2):\n"
        "    return 2 * np.arcsin(np.sqrt(p1)) - 2 * np.arcsin(np.sqrt(p2))\n"
        "\n"
        "h = abs(cohens_h(p_B, p_A))\n"
        "print(f\"Размер эффекта Cohen's h: {h:.4f}\")\n"
        "if h < 0.2:\n"
        "    print('Интерпретация: маленький эффект')\n"
        "elif h < 0.5:\n"
        "    print('Интерпретация: средний эффект')\n"
        "else:\n"
        "    print('Интерпретация: большой эффект')\n"
        "\n"
        "# Оценка мощности теста (Монте-Карло)\n"
        "np.random.seed(0)\n"
        "n_sim = 2000\n"
        "reject = 0\n"
        "for _ in range(n_sim):\n"
        "    a = np.random.binomial(1, true_conv_A, n_A)\n"
        "    b = np.random.binomial(1, true_conv_B, n_B)\n"
        "    xa, xb = a.sum(), b.sum()\n"
        "    pp = (xa + xb) / (n_A + n_B)\n"
        "    se = np.sqrt(pp * (1 - pp) * (1/n_A + 1/n_B))\n"
        "    z = (xb/n_B - xa/n_A) / se\n"
        "    if 2 * (1 - stats.norm.cdf(abs(z))) < alpha:\n"
        "        reject += 1\n"
        "power = reject / n_sim\n"
        "print(f'\\nОценённая мощность теста (Монте-Карло): {power*100:.1f}%')\n"
        "print('Рекомендуемый порог мощности: 80%')"
    ))

    cells.append(md(
        "## 6. Байесовский взгляд на A/B-тест (Beta-Binomial)\n"
        "\n"
        "Используем сопряжённое априорное распределение **Beta** для конверсии. "
        "При наблюдении $x$ успехов из $n$ испытаний апостериорное распределение:\n"
        "\n"
        "$$p \\mid \\text{data} \\sim \\text{Beta}(\\alpha_0 + x, \\; \\beta_0 + n - x)$$\n"
        "\n"
        "Возьмём неинформативное априорное $\\text{Beta}(1, 1)$ и оценим "
        "$P(p_B > p_A)$ методом Монте-Карло."
    ))

    cells.append(code(
        "# Байесовский A/B: Beta-Binomial\n"
        "alpha0, beta0 = 1, 1  # неинформативное априорное Beta(1,1)\n"
        "\n"
        "post_A = stats.beta(alpha0 + s_A, beta0 + n_A - s_A)\n"
        "post_B = stats.beta(alpha0 + s_B, beta0 + n_B - s_B)\n"
        "\n"
        "# Сэмплирование из апостериорных распределений\n"
        "np.random.seed(7)\n"
        "samples_A = post_A.rvs(100000)\n"
        "samples_B = post_B.rvs(100000)\n"
        "prob_B_better = (samples_B > samples_A).mean()\n"
        "expected_uplift = (samples_B - samples_A).mean()\n"
        "\n"
        "print('Байесовский анализ A/B-теста')\n"
        "print('=' * 60)\n"
        "print(f'P(конверсия B > конверсия A) = {prob_B_better*100:.2f}%')\n"
        "print(f'Ожидаемый прирост конверсии: {expected_uplift*100:.2f} п.п.')\n"
        "\n"
        "# Визуализация апостериорных распределений\n"
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
        "x = np.linspace(0.09, 0.17, 500)\n"
        "axes[0].plot(x, post_A.pdf(x), label='A (контроль)', color='steelblue')\n"
        "axes[0].plot(x, post_B.pdf(x), label='B (новая)', color='coral')\n"
        "axes[0].fill_between(x, post_A.pdf(x), alpha=0.3, color='steelblue')\n"
        "axes[0].fill_between(x, post_B.pdf(x), alpha=0.3, color='coral')\n"
        "axes[0].set_xlabel('Конверсия p')\n"
        "axes[0].set_ylabel('Плотность апостериорного распределения')\n"
        "axes[0].set_title('Апостериорные распределения конверсий')\n"
        "axes[0].legend()\n"
        "\n"
        "diff = samples_B - samples_A\n"
        "axes[1].hist(diff, bins=60, color='green', alpha=0.7, edgecolor='black')\n"
        "axes[1].axvline(0, color='red', linestyle='--', linewidth=2, label='Нет разницы')\n"
        "axes[1].set_xlabel('Разница конверсий (B - A)')\n"
        "axes[1].set_ylabel('Частота')\n"
        "axes[1].set_title(f'Распределение разницы: P(B>A)={prob_B_better*100:.1f}%')\n"
        "axes[1].legend()\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ))

    cells.append(md(
        "## 7. Выводы и рекомендации\n"
        "\n"
        "Соберём результаты классического и байесовского подходов в единый вывод."
    ))

    cells.append(code(
        "print('ИТОГОВЫЙ ОТЧЁТ ПО A/B-ТЕСТУ')\n"
        "print('=' * 60)\n"
        "print(f'Конверсия A: {p_A*100:.2f}%  (n={n_A})')\n"
        "print(f'Конверсия B: {p_B*100:.2f}%  (n={n_B})')\n"
        "print(f'Абсолютный прирост: {(p_B-p_A)*100:.2f} п.п.')\n"
        "print(f'Относительный прирост: {(p_B/p_A-1)*100:.1f}%')\n"
        "print('-' * 60)\n"
        "print(f'z-тест p-значение: {p_value:.4f}')\n"
        "print(f\"Размер эффекта (Cohen's h): {h:.3f}\")\n"
        "print(f'P(B > A) по Байесу: {prob_B_better*100:.1f}%')\n"
        "print('-' * 60)\n"
        "if p_value < alpha and prob_B_better > 0.95:\n"
        "    print('РЕКОМЕНДАЦИЯ: Внедрить версию B — эффект статистически значим')\n"
        "    print('и подтверждён байесовским анализом.')\n"
        "else:\n"
        "    print('РЕКОМЕНДАЦИЯ: Недостаточно данных для уверенного решения,')\n"
        "    print('стоит продолжить сбор данных.')"
    ))

    cells.append(md(
        "## Упражнения\n"
        "\n"
        "### Упражнение 1: Односторонний тест\n"
        "1. Переформулируйте гипотезу как одностороннюю ($H_1: p_B > p_A$)\n"
        "2. Как изменится p-значение и вывод?\n"
        "\n"
        "### Упражнение 2: Анализ вторичной метрики\n"
        "1. Проверьте гипотезу о равенстве среднего времени на сайте (t-тест)\n"
        "2. Постройте доверительный интервал для разницы средних\n"
        "\n"
        "### Упражнение 3: Планирование размера выборки\n"
        "1. Какой размер выборки нужен для мощности 80% при эффекте +1.5 п.п.?\n"
        "2. Используйте `statsmodels` или формулу для пропорций\n"
        "\n"
        "### Упражнение 4: Влияние априорного распределения\n"
        "1. Повторите байесовский анализ с информативным априорным Beta(12, 88)\n"
        "2. Как меняется $P(B>A)$ при малом объёме данных (первые 200 пользователей)?\n"
        "\n"
        "---\n"
        "\n"
        "**Решения** можно найти в ноутбуке `solutions/16_Solutions.ipynb`"
    ))

    return build_notebook(cells)


# =====================================================================
# ПРОЕКТ 17: Байесовский классификатор спама
# =====================================================================
def project_spam_classifier():
    cells = []

    cells.append(md(
        "# Байесовский классификатор спама\n"
        "\n"
        "## Прикладной проект: Наивный байесовский фильтр электронной почты\n"
        "\n"
        "В этом ноутбуке мы применим знания из **Модуля 1 (теорема Байеса)** и "
        "**Модуля 4 (MLE, байесовский вывод)** для построения классификатора спама "
        "с нуля.\n"
        "\n"
        "### Идея наивного байесовского классификатора:\n"
        "\n"
        "$$P(\\text{spam} \\mid \\text{слова}) = \\frac{P(\\text{слова} \\mid \\text{spam})\\,P(\\text{spam})}{P(\\text{слова})}$$\n"
        "\n"
        "«Наивное» предположение — условная независимость слов при заданном классе.\n"
        "\n"
        "### Содержание:\n"
        "1. Генерация и загрузка данных\n"
        "2. Exploratory Data Analysis (EDA)\n"
        "3. Оценка вероятностей (MLE) со сглаживанием Лапласа\n"
        "4. Реализация классификатора\n"
        "5. Оценка качества: precision, recall, матрица ошибок\n"
        "6. Апостериорные вероятности и интерпретация\n"
        "7. Выводы"
    ))

    cells.append(code(
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n"
        "from collections import Counter\n"
        "import warnings\n"
        "warnings.filterwarnings('ignore')\n"
        "\n"
        "plt.style.use('seaborn-v0_8-whitegrid')\n"
        "sns.set_palette('husl')\n"
        "\n"
        "print('Библиотеки успешно загружены!')"
    ))

    cells.append(md(
        "## 1. Генерация и загрузка данных\n"
        "\n"
        "Сгенерируем синтетические письма. У спама и обычных писем (ham) разные "
        "вероятности появления слов.\n"
        "\n"
        "### Структура данных:\n"
        "- **text**: Текст письма (набор слов)\n"
        "- **label**: Метка класса (`spam` / `ham`)"
    ))

    cells.append(code(
        "# Генерация синтетических писем\n"
        "np.random.seed(42)\n"
        "\n"
        "# Словарь: вероятность слова в спаме и в ham\n"
        "#                слово     P(word|spam)  P(word|ham)\n"
        "vocab = {\n"
        "    'выигрыш':      (0.30, 0.02),\n"
        "    'бесплатно':    (0.35, 0.03),\n"
        "    'кредит':       (0.25, 0.02),\n"
        "    'скидка':       (0.28, 0.05),\n"
        "    'срочно':       (0.22, 0.04),\n"
        "    'деньги':       (0.30, 0.06),\n"
        "    'приз':         (0.26, 0.02),\n"
        "    'встреча':      (0.03, 0.25),\n"
        "    'проект':       (0.04, 0.28),\n"
        "    'отчёт':        (0.03, 0.24),\n"
        "    'коллега':      (0.02, 0.20),\n"
        "    'договор':      (0.05, 0.22),\n"
        "    'привет':       (0.08, 0.30),\n"
        "    'спасибо':      (0.06, 0.28),\n"
        "    'вопрос':       (0.07, 0.26),\n"
        "}\n"
        "words = list(vocab.keys())\n"
        "\n"
        "def generate_email(is_spam):\n"
        "    idx = 0 if is_spam else 1\n"
        "    tokens = [w for w in words if np.random.rand() < vocab[w][idx]]\n"
        "    if not tokens:  # письмо не бывает пустым\n"
        "        tokens = [np.random.choice(words)]\n"
        "    return ' '.join(tokens)\n"
        "\n"
        "n_spam, n_ham = 400, 600\n"
        "data = []\n"
        "for _ in range(n_spam):\n"
        "    data.append({'text': generate_email(True), 'label': 'spam'})\n"
        "for _ in range(n_ham):\n"
        "    data.append({'text': generate_email(False), 'label': 'ham'})\n"
        "\n"
        "df = pd.DataFrame(data).sample(frac=1, random_state=42).reset_index(drop=True)\n"
        "\n"
        "print('Данные электронной почты')\n"
        "print('=' * 60)\n"
        "print(f'Всего писем: {len(df)}')\n"
        "print(f'Спам: {(df[\"label\"] == \"spam\").sum()}')\n"
        "print(f'Ham:  {(df[\"label\"] == \"ham\").sum()}')\n"
        "print(f'\\nПримеры писем:')\n"
        "print(df.head(8).to_string(index=False))"
    ))

    cells.append(md(
        "## 2. Exploratory Data Analysis (EDA)\n"
        "\n"
        "Посмотрим, какие слова наиболее характерны для спама и ham."
    ))

    cells.append(code(
        "# Подсчёт частот слов по классам\n"
        "spam_words = Counter()\n"
        "ham_words = Counter()\n"
        "\n"
        "for _, row in df.iterrows():\n"
        "    tokens = row['text'].split()\n"
        "    if row['label'] == 'spam':\n"
        "        spam_words.update(tokens)\n"
        "    else:\n"
        "        ham_words.update(tokens)\n"
        "\n"
        "freq_df = pd.DataFrame({\n"
        "    'spam': pd.Series(spam_words),\n"
        "    'ham': pd.Series(ham_words)\n"
        "}).fillna(0).astype(int)\n"
        "freq_df = freq_df.loc[words]\n"
        "\n"
        "print('Частота слов по классам:')\n"
        "print(freq_df)\n"
        "\n"
        "# Визуализация\n"
        "fig, axes = plt.subplots(1, 2, figsize=(14, 6))\n"
        "\n"
        "freq_df.sort_values('spam', ascending=True).plot.barh(\n"
        "    y='spam', ax=axes[0], color='crimson', alpha=0.7, legend=False)\n"
        "axes[0].set_xlabel('Частота в спаме')\n"
        "axes[0].set_title('Частота слов в СПАМЕ')\n"
        "\n"
        "freq_df.sort_values('ham', ascending=True).plot.barh(\n"
        "    y='ham', ax=axes[1], color='seagreen', alpha=0.7, legend=False)\n"
        "axes[1].set_xlabel('Частота в ham')\n"
        "axes[1].set_title('Частота слов в HAM')\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ))

    cells.append(md(
        "## 3. Оценка вероятностей (MLE) со сглаживанием Лапласа\n"
        "\n"
        "Оценим параметры методом максимального правдоподобия. Чтобы избежать нулевых "
        "вероятностей для слов, не встретившихся в классе, применим **сглаживание Лапласа**:\n"
        "\n"
        "$$P(w \\mid c) = \\frac{\\text{count}(w, c) + \\alpha}{N_c + \\alpha \\cdot |V|}$$\n"
        "\n"
        "где $\\alpha=1$ — параметр сглаживания, $|V|$ — размер словаря, "
        "$N_c$ — суммарное число слов класса $c$."
    ))

    cells.append(code(
        "# Разделение на обучающую и тестовую выборки\n"
        "train = df.sample(frac=0.7, random_state=1)\n"
        "test = df.drop(train.index).reset_index(drop=True)\n"
        "train = train.reset_index(drop=True)\n"
        "print(f'Обучающая выборка: {len(train)}, тестовая: {len(test)}')\n"
        "\n"
        "# Априорные вероятности классов P(spam), P(ham)\n"
        "p_spam = (train['label'] == 'spam').mean()\n"
        "p_ham = (train['label'] == 'ham').mean()\n"
        "print(f'\\nАприорные вероятности:')\n"
        "print(f'P(spam) = {p_spam:.3f}')\n"
        "print(f'P(ham)  = {p_ham:.3f}')\n"
        "\n"
        "# Подсчёт слов на обучающей выборке\n"
        "sw = Counter()\n"
        "hw = Counter()\n"
        "for _, row in train.iterrows():\n"
        "    tok = row['text'].split()\n"
        "    (sw if row['label'] == 'spam' else hw).update(tok)\n"
        "\n"
        "alpha = 1.0\n"
        "V = len(words)\n"
        "N_spam = sum(sw.values())\n"
        "N_ham = sum(hw.values())\n"
        "\n"
        "def word_prob(word, cls):\n"
        "    if cls == 'spam':\n"
        "        return (sw[word] + alpha) / (N_spam + alpha * V)\n"
        "    return (hw[word] + alpha) / (N_ham + alpha * V)\n"
        "\n"
        "prob_table = pd.DataFrame({\n"
        "    'P(w|spam)': [word_prob(w, 'spam') for w in words],\n"
        "    'P(w|ham)': [word_prob(w, 'ham') for w in words],\n"
        "}, index=words)\n"
        "prob_table['log_ratio'] = np.log(prob_table['P(w|spam)'] / prob_table['P(w|ham)'])\n"
        "print('\\nОценённые вероятности слов (MLE + сглаживание):')\n"
        "print(prob_table.round(4))"
    ))

    cells.append(md(
        "## 4. Реализация классификатора\n"
        "\n"
        "Чтобы избежать переполнения при перемножении малых вероятностей, работаем в "
        "**логарифмах**:\n"
        "\n"
        "$$\\log P(c \\mid \\text{слова}) \\propto \\log P(c) + \\sum_i \\log P(w_i \\mid c)$$"
    ))

    cells.append(code(
        "# Наивный байесовский классификатор в лог-пространстве\n"
        "def classify(text, return_proba=False):\n"
        "    tokens = [w for w in text.split() if w in vocab]\n"
        "    log_spam = np.log(p_spam)\n"
        "    log_ham = np.log(p_ham)\n"
        "    for w in tokens:\n"
        "        log_spam += np.log(word_prob(w, 'spam'))\n"
        "        log_ham += np.log(word_prob(w, 'ham'))\n"
        "    # Нормализация в вероятность через log-sum-exp\n"
        "    m = max(log_spam, log_ham)\n"
        "    p_s = np.exp(log_spam - m)\n"
        "    p_h = np.exp(log_ham - m)\n"
        "    proba_spam = p_s / (p_s + p_h)\n"
        "    label = 'spam' if proba_spam >= 0.5 else 'ham'\n"
        "    if return_proba:\n"
        "        return label, proba_spam\n"
        "    return label\n"
        "\n"
        "# Примеры классификации\n"
        "examples = [\n"
        "    'выигрыш бесплатно приз деньги',\n"
        "    'привет коллега отчёт проект',\n"
        "    'скидка срочно кредит',\n"
        "    'спасибо вопрос встреча',\n"
        "]\n"
        "print('Примеры классификации')\n"
        "print('=' * 60)\n"
        "for text in examples:\n"
        "    label, proba = classify(text, return_proba=True)\n"
        "    print(f'[{label.upper():4}] P(spam)={proba:.3f}  <- \"{text}\"')"
    ))

    cells.append(md(
        "## 5. Оценка качества\n"
        "\n"
        "Оценим классификатор на тестовой выборке. Основные метрики:\n"
        "- **Accuracy** — доля правильных ответов\n"
        "- **Precision** — $\\frac{TP}{TP+FP}$ (какая часть писем, помеченных как спам, действительно спам)\n"
        "- **Recall** — $\\frac{TP}{TP+FN}$ (какую часть спама мы поймали)\n"
        "- **F1** — гармоническое среднее precision и recall"
    ))

    cells.append(code(
        "# Предсказания на тесте\n"
        "test = test.copy()\n"
        "test['pred'] = test['text'].apply(classify)\n"
        "\n"
        "# Матрица ошибок (spam — положительный класс)\n"
        "TP = ((test['label'] == 'spam') & (test['pred'] == 'spam')).sum()\n"
        "TN = ((test['label'] == 'ham') & (test['pred'] == 'ham')).sum()\n"
        "FP = ((test['label'] == 'ham') & (test['pred'] == 'spam')).sum()\n"
        "FN = ((test['label'] == 'spam') & (test['pred'] == 'ham')).sum()\n"
        "\n"
        "accuracy = (TP + TN) / len(test)\n"
        "precision = TP / (TP + FP) if (TP + FP) else 0\n"
        "recall = TP / (TP + FN) if (TP + FN) else 0\n"
        "f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0\n"
        "\n"
        "print('Метрики качества на тестовой выборке')\n"
        "print('=' * 60)\n"
        "print(f'Accuracy:  {accuracy:.3f}')\n"
        "print(f'Precision: {precision:.3f}')\n"
        "print(f'Recall:    {recall:.3f}')\n"
        "print(f'F1-score:  {f1:.3f}')\n"
        "\n"
        "# Визуализация матрицы ошибок\n"
        "cm = np.array([[TN, FP], [FN, TP]])\n"
        "fig, ax = plt.subplots(figsize=(6, 5))\n"
        "sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,\n"
        "            xticklabels=['ham', 'spam'], yticklabels=['ham', 'spam'], ax=ax)\n"
        "ax.set_xlabel('Предсказание')\n"
        "ax.set_ylabel('Истинный класс')\n"
        "ax.set_title('Матрица ошибок')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ))

    cells.append(md(
        "## 6. Апостериорные вероятности и интерпретация\n"
        "\n"
        "Посмотрим на распределение апостериорной вероятности $P(\\text{spam}\\mid\\text{текст})$ "
        "и на самые «спамные» слова по логарифму отношения вероятностей."
    ))

    cells.append(code(
        "# Апостериорные вероятности на тесте\n"
        "test['proba_spam'] = test['text'].apply(lambda t: classify(t, return_proba=True)[1])\n"
        "\n"
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
        "\n"
        "# Распределение P(spam) по истинным классам\n"
        "axes[0].hist(test[test['label'] == 'ham']['proba_spam'], bins=25,\n"
        "             alpha=0.6, label='истинный ham', color='seagreen')\n"
        "axes[0].hist(test[test['label'] == 'spam']['proba_spam'], bins=25,\n"
        "             alpha=0.6, label='истинный spam', color='crimson')\n"
        "axes[0].axvline(0.5, color='black', linestyle='--', label='порог 0.5')\n"
        "axes[0].set_xlabel('P(spam | текст)')\n"
        "axes[0].set_ylabel('Количество писем')\n"
        "axes[0].set_title('Распределение апостериорной вероятности')\n"
        "axes[0].legend()\n"
        "\n"
        "# Самые информативные слова (log-ratio)\n"
        "sorted_ratio = prob_table.sort_values('log_ratio')\n"
        "colors = ['crimson' if v > 0 else 'seagreen' for v in sorted_ratio['log_ratio']]\n"
        "axes[1].barh(sorted_ratio.index, sorted_ratio['log_ratio'], color=colors, alpha=0.7)\n"
        "axes[1].axvline(0, color='black', linewidth=1)\n"
        "axes[1].set_xlabel('log P(w|spam) / P(w|ham)')\n"
        "axes[1].set_title('Информативность слов (>0 = спам, <0 = ham)')\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ))

    cells.append(md(
        "## 7. Выводы\n"
        "\n"
        "Собираем итоговый отчёт по классификатору."
    ))

    cells.append(code(
        "print('ИТОГОВЫЙ ОТЧЁТ ПО КЛАССИФИКАТОРУ СПАМА')\n"
        "print('=' * 60)\n"
        "print(f'Обучающая выборка: {len(train)} писем')\n"
        "print(f'Тестовая выборка:  {len(test)} писем')\n"
        "print(f'Размер словаря:    {V} слов')\n"
        "print('-' * 60)\n"
        "print(f'Accuracy:  {accuracy:.1%}')\n"
        "print(f'Precision: {precision:.1%}')\n"
        "print(f'Recall:    {recall:.1%}')\n"
        "print(f'F1-score:  {f1:.3f}')\n"
        "print('-' * 60)\n"
        "print('Классификатор построен полностью с нуля на основе теоремы Байеса')\n"
        "print('и оценки максимального правдоподобия со сглаживанием Лапласа.')"
    ))

    cells.append(md(
        "## Упражнения\n"
        "\n"
        "### Упражнение 1: Влияние сглаживания\n"
        "1. Как изменится качество при $\\alpha = 0.01$ и $\\alpha = 10$?\n"
        "2. Постройте график зависимости F1 от $\\alpha$\n"
        "\n"
        "### Упражнение 2: Порог классификации\n"
        "1. Постройте ROC-кривую, меняя порог P(spam)\n"
        "2. Как выбрать порог, если ложная пометка ham как spam особенно нежелательна?\n"
        "\n"
        "### Упражнение 3: Несбалансированные классы\n"
        "1. Сгенерируйте данные с соотношением 10% спама и 90% ham\n"
        "2. Как меняются precision и recall? Почему accuracy обманчива?\n"
        "\n"
        "### Упражнение 4: Сравнение с библиотекой\n"
        "1. Обучите `sklearn.naive_bayes.MultinomialNB` на тех же данных\n"
        "2. Сравните результаты с вашей реализацией\n"
        "\n"
        "---\n"
        "\n"
        "**Решения** можно найти в ноутбуке `solutions/17_Solutions.ipynb`"
    ))

    return build_notebook(cells)


if __name__ == '__main__':
    import os
    base = os.path.dirname(os.path.abspath(__file__))

    nb16 = project_ab_testing()
    path16 = os.path.join(base, '16_AB_Testing.ipynb')
    with open(path16, 'w', encoding='utf-8') as f:
        nbf.write(nb16, f)
    print(f'Создан: {path16} ({len(nb16.cells)} ячеек)')

    nb17 = project_spam_classifier()
    path17 = os.path.join(base, '17_Spam_Classifier.ipynb')
    with open(path17, 'w', encoding='utf-8') as f:
        nbf.write(nb17, f)
    print(f'Создан: {path17} ({len(nb17.cells)} ячеек)')
